---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare artifact
        run: |
          cd /home/runner/work/home-assistant-pse/home-assistant-pse/custom_components/pse
          zip pse.zip -r ./
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: pse.zip