name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: ZIP files
        run: |
          cd /home/runner/work/home-assistant-pse/home-assistant-pse/custom_components/pse
          zip pse.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.4.1
        permissions:
          # write permission is required to create a github release
          contents: write
          # write permission is required for autolabeler
          # otherwise, read permission is required at least
          pull-requests: write
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/home-assistant-pse/home-assistant-pse/custom_components/pse/pse.zip
          asset_name: pse.zip
          tag: ${{ github.ref }}
          overwrite: true
